### PR TITLE
Added support for deploying through docker - https://www.docker.com

### PR DESCRIPTION
**Pull request by programster**
To deploy, all you need to do is go into the `docker` folder and run:

```
bash build.sh
bash run-container.sh
```

Once `run-container.sh` has been executed there will be a `data` folder at the same level as the project source code. You can edit your database configuration in database.php and SMTP details within constants.php in there. This folder also acts as a volume so that upload files persist across containers.
- All file uploads are persistant across containers being killed and spawned.
- supports https/ssl

### CODE REVIEW

**Comment by raphaelcasimir** [comment]
Hello,
Thank you for the very simple installation process... But it seems that it doesn't work. On 80 or 443 (with ssl certs correctly inserted). It just makes a white page with the orangescrum favicon. Do you have any idea why it does this and how to fix it ? Does it happen with you ?
Running Docker on Ubuntu 14.04.3

**Comment by programster** [comment]
Hey @raphaelcasimir,
I just retried on this computer and it works fine for me but then again I haven't tried putting in my own ssl certs, only using the auto generated ones. 

* Does it work for you on port 80 and its just 443 that is not?
* I take it that you ran the container with `bash run-container.sh` in the docker folder? This maps your ports and volume for you.
* Have you made sure to comment out `bind-address` in your database's my.cnf file?
* Have you made sure the container started correctly? E.g. what is the output of `docker ps`. The container will not start if something else is using the ports, such as Apache.
* Have you made sure to update your `database.php` file to point to your databases's IP and is not using something like localhost or 127.0.0.1? This database.php file will be in the "data" folder created at the same directory level as the git repository you cloned.

**Comment by programster** [comment]
If you are still having difficulties with this, perhaps we could arrange a time to discuss over Google hangouts? After this has been pulled, I want to merge in automated database migrations so the user never has to do anything.

**Comment by raphaelcasimir** [comment]
With pleasure. I am available after 18:20 hour of Paris (I think it is
synchronised with universal time).

**Comment by programster** [comment]
@raphaelcasimir I just ran into this same issue when I re-deployed on Amazon linux. When I looked inside the container I could see that the volume wasn't being mounted which is most odd. When I Googled this I found [this bug report](https://github.com/docker/docker/issues/5489) which told me:

>... just to make it clear what it was for people who might have hard time finding it in the thread:
>
>The solution is to restart the docker daemon after mounting filesystems which contain paths later mounted as volumes inside the containers, otherwise the data changes only inside the container and changes are not visible on the host filesystem.
>
>This should be clearly documented inside the Volumes section of the docker run command until Docker can handle it automatically.

I restarted the daemon and it worked. When I finish work today I will look into whether I can find a workaround/solution for this. We can't expect our users to restart the daemon.

**Comment by raphaelcasimir** [comment]
Hello,
I've tried your method and it seems to work but the server sends me back
that I've not configured the database. I thought the database server were
included into the container, were that true ?
If not, can you explain me how to do it (if that does not bother you) ? I
am already running a mongoDB container on my server, can I use it ?

Thanks a lot for all your help.

(I've changed permissions as asked in the red lines)




2015-11-10 11:25 GMT+01:00 Programster <notifications@github.com>:

**Comment by programster** [comment]
@raphaelcasimir The container in this pull request does not contain the database backend. For the time being, the container will create a "data" directory volume which contains a database.php file. You have to update that file with the details of your MySql database. Can you run Orangescrum on MongoDB? I've only ever tried with MySql which pretty straight forward. The only thing you need to remember is update the `my.cnf` config file of the database so its not just listening to localhost, but to outside connections as well.

In the future, I will get migrations, and then the database inside the container or running as another linked container. I would prefer having the database inside the same container so that there is only one volume for the user and a very simple solution, however the architecture might be better to have a seperate container for the database, which would be more flexible for those users who want to run the database on a completely separate host or dedicated system.

**Comment by raphaelcasimir** [comment]
Ok. You can then make two different  scripts depending on the type of the
installation...
Thanks a lot for your help

**Comment by programster** [comment]
@raphaelcasimir can you link me to whatever instructions tell you how to install with Mongo? I've looked around the net and everything I have found rely on MySQL.

**Comment by raphaelcasimir** [comment]
No that's just a coincidence I am running rocket.chat which uses mongo so I
wondered if it was possible it for orangescrum also

**Comment by raphaelcasimir** [comment]
Ok, so I linked correctly I think the mysql and orangescrum docker, so no more starting page with red writing on it, no it is just blank... I am turning crazy. I must have the orangescrum environment running for monday, and I am thinking about taking a blank ubuntu server container and installing orangescrum in it... Do you think it is a good idea ?

**Pull request closed without merging**
